### PR TITLE
Fix queue.yaml example and refer to pysqa documentation.

### PR DESCRIPTION
**Pull request by niklassiemer**

### CODE REVIEW

**Review by ligerzero-ai — CHANGES_REQUESTED** [review]
Actually - can we make these changes in the `docs/source/installation.rst` It's super dumb - but these don't actually change what appears on the website. The two separate docs are actually redundant. I've only kept them because Jan and I were discussing the best way to have installation formatted, and at some point we may need separate entries on the menu for quickstart and detailed installation instructions.

What's currently on the website is still an intermediate solution.

I'll fix it in this branch myself tomorrow.

**Comment by niklassiemer** [comment]
I actually do not get what you are referring to? in the current readthedocs of pyiron it is essentially broken to copy the yaml and this should fix it?! I absolutely agree, that we should have 
1) synchronized docs for our packages
2) document the most recent (working!) solutions
But right now, we have this flaw in?!

**Comment by ligerzero-ai** [comment]
Hey @niklassiemer, hopefully the new pull (I was lazy and just started a new branch). 

To make the changes appear, you actulaly have to change the installation.rst the other files don't actually appear on the website - they are just placeholders that are hidden for now.

**Comment by ligerzero-ai** [comment]
Superceded by #1498 (which is now merged) - Closing pull

**Pull request closed without merging**
