### PR TITLE
number of electronic steps changed

### PR DESCRIPTION
**Pull request by samwaseda**
Following [this discussion](https://github.com/pyiron/pyiron/issues/777) and last pyiron meeting.

### CODE REVIEW

**Comment by samwaseda** [comment]
Now minimisation is 60 and static calculation is 100.

**Comment by jan-janssen** [comment]
https://github.com/pyiron/pyiron/blob/electronic_steps/tests/sphinx/test_base.py#L187

**Comment by jan-janssen** [comment]
https://github.com/pyiron/pyiron/blob/electronic_steps/tests/sphinx/test_base.py#L317

**Comment by samwaseda** [comment]
> But please update the tests as well.

Yes yes no worries I was first waiting for them to fail to see which ones have to be updated.

**Pull request merged**
