### PR TITLE
Sphinx interactive energy type

### PR DESCRIPTION
**Pull request by liamhuber**
Let's return a float instead of np.array(float).

### CODE REVIEW

**Comment by samwaseda** [comment]
Why array? It returns one value for each `get energy`

**Comment by liamhuber** [comment]
Yes. This is exactly my problem. Instead of returning the one value as a float, it returns it as a float wrapped in an array. Will it break the code elsewhere to get rid of this array wrapping? Was there some rational for wrapping it to start with?

**Comment by samwaseda** [comment]
But this one expects one value

https://github.com/pyiron/pyiron/blob/72e4c16a4c9d79344e1011a90e4cebcbe302ad44/pyiron/atomistics/job/interactive.py#L182

**Comment by samwaseda** [comment]
Oh sorry I thought you were doing exactly the opposite

**Comment by liamhuber** [comment]
I don't understand if we disagree about anything or not.

Note:
```python

foo = np.array(1)
bar = np.array(2)
baz = []
for x in [foo, bar]:
    baz.append(x)
print(baz)
print(np.array(baz))

> [array(1), array(2)]
> [1 2]
```

**Comment by liamhuber** [comment]
Ahhh, good! No, I am doing the opposite of the opposite ;)

**Comment by liamhuber** [comment]
I think my example a couple comments above probably shows how we got away without noticing this for so long though.

**Comment by samwaseda** [comment]
I guess I had never used this one as such, so you're probably right

**Comment by liamhuber** [comment]
Cool. I'll let the tests run, but provided they come back green I'll merge.

**Pull request merged**
