### PR TITLE
Restructure installation documentation

### PR DESCRIPTION
**Pull request by niklassiemer**

### CODE REVIEW

**Comment by jan-janssen** [comment]
@niklassiemer Does it make sense to discuss this in the infrastructure meeting tomorrow? If that is the case then I would like @ligerzero-ai to join as well so we can develop one consistent strategy for the documentation.

**Comment by niklassiemer** [comment]
Yes, either there or in the pyiron meeting?

**Comment by ligerzero-ai** [comment]
Sure, I'll join. 9am right?

**Comment by aageo25** [comment]
I would also like to contribute here. I am going trough the installation to install of pyiron in my Univ HPC. I can keep and eye on the bugs/broken links on the webpage and fix them. 

This, of course, only if you allow me to do it.

**Comment by aageo25** [comment]
> > I would also like to contribute here. I am going trough the installation to install of pyiron in my Univ HPC. I can keep and eye on the bugs/broken links on the webpage and fix them.
> > This, of course, only if you allow me to do it.
> 
> Please let me know what needs fixing. I hope that you test out the "quickstart installation" in particular - I have had complaints that it is still broken in some places but I cannot reproduce them on my machine(s). Perhaps it is some things that I am doing that are not actually explicitly in the guide.

One thing I realized is that the examples for the `.pyiron` file are not consistent throughout the page. The same goes for the `sbatch` file examples (correct me if I am not using the right technical terms referencing the files contents. I'm new to collaborative coding).

I don't know if that's super important, but it is one thing that I notice. In other pages in the Docs, there are some broken links. But that's perhaps better raising the issue elsewhere.

**Comment by ligerzero-ai** [comment]
> > > I would also like to contribute here. I am going trough the installation to install of pyiron in my Univ HPC. I can keep and eye on the bugs/broken links on the webpage and fix them.
> > > This, of course, only if you allow me to do it.
> > 
> > 
> > Please let me know what needs fixing. I hope that you test out the "quickstart installation" in particular - I have had complaints that it is still broken in some places but I cannot reproduce them on my machine(s). Perhaps it is some things that I am doing that are not actually explicitly in the guide.
> 
> One thing I realized is that the examples for the `.pyiron` file are not consistent throughout the page. The same goes for the `sbatch` file examples (correct me if I am not using the right technical terms referencing the files contents. I'm new to collaborative coding).
> 
> I don't know if that's super important, but it is one thing that I notice. In other pages in the Docs, there are some broken links. But that's perhaps better raising the issue elsewhere.

Thanks for catching these details! 

I found that the most important thing to mention about the slurm templates is that the user should just copy an existing working job and replace the fields where possible with the jinja {{...}} strings. Perhaps that needs to be the most prominent thing. 

Maybe a comment in the code field should catch users attention instead of glossing over the text between the steps.

As for the `.pyiron` - the old instructions are very mpie-centric, where there is no small file or storage limit on /home, which is rarely the case on other systems. I have been meaning to change the older documentation, so that it is consistent, but at the same time I haven't quite gotten around to it, or know if others will agree to it.

**Comment by ligerzero-ai** [comment]
lgtm, lets get this merged?

**Pull request merged**
