### PR TITLE
Use papermill - https://github.com/nteract/papermill

### PR DESCRIPTION
**Pull request by jan-janssen**
Rather than our own class for manipulating input parameters in jupyter notebooks.

### CODE REVIEW

**Comment by samwaseda** [comment]
Can you attach a notebook or the commands for me to understand how it works?

**Comment by jan-janssen** [comment]
https://papermill.readthedocs.io/en/latest/usage-parameterize.html#how-parameters-work

**Comment by samwaseda** [comment]
And does this work when a notebook is submitted to the cluster?

**Comment by jan-janssen** [comment]
This part still needs to be done, but it is definitely possible. https://papermill.readthedocs.io/en/latest/usage-execute.html

**Comment by samwaseda** [comment]
But the main idea of `Notebook` class is to pass parameters to the notebook which is submitted. Otherwise I don't think it's particularly important to send parameters from one notebook to another (or even I find it dangerous to work this way).

**Pull request closed without merging**
