### PR TITLE
Pyscal consistency

### PR DESCRIPTION
**Pull request by liamhuber**
Very minor touchups to the wonderful [switch from ovito to pyscal](https://github.com/pyiron/pyiron/pull/1192)

### CODE REVIEW

**Comment by liamhuber** [comment]
I really appreciate [this switch](https://github.com/pyiron/pyiron/pull/1192). Just this weekend I ran into needing voronoi analysis on a system that doesn't have ovito, so the timing couldn't be better 👍

**Comment by liamhuber** [comment]
I don't think this requires review, nor even that it stay up -- it's effectively just documentation improvement.

As soon as the tests complete I'll merge it. I just with through the PR process so there's a clean record of the change.

**Review by jan-janssen — APPROVED** [review]
Looks good to me - sorry seems like I was a bit tired after this week.

**Comment by liamhuber** [comment]
@jan-janssen no worries! It happens and the beauty of this workflow is that patches like this are so easy 🙂 lots of great changes lately!

**Pull request merged**
