### PR TITLE
Use Docker file for mybinder

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Comment by muh-hassani** [comment]
@jan-janssen why did you close this?

**Comment by jan-janssen** [comment]
Because mybinder still triggers a new build every time we commit to the master branch, the only way to change this is a separate repository. Still it might make sense to have a docker container with all the dependencies, that would also accelerate our testing infrastructure.

**Comment by muh-hassani** [comment]
Oh, I see. So it can't be used in this case :(

**Comment by jan-janssen** [comment]
I created a pull request to build only the pyiron dependencies.

**Pull request closed without merging**
