### PR TITLE
Documentation via jupyter books

### PR DESCRIPTION
**Pull request by niklassiemer**
Using jupyter-books to build the documentation.
So far using the make.sh file of docs -  I do not know how this is handled on travis(?) 
Not updating environment, yet

### CODE REVIEW

**Comment by niklassiemer** [comment]
Also I would appreciate some help to make the binder buttons work as expected.

**Comment by ashtonmv** [comment]
Thanks for working on this Niklas; it looks great!

Regarding mybinder - I'm not sure if it's of any use, but I just published a small tool [nbjuniper](https://github.com/ashtonmv/nbjuniper), which converts IPython notebooks to executable HTML files by linking them to a MyBinder backend under the hood.

Maybe you can play around with it and see if it's at all useful within the jupyter books workflow you've set up?

```sh
conda install -c conda-forge nbjuniper
nbjuniper -h  # in case you're curious, README has more details
nbjuniper -r pyiron/docs --repo pyiron/pyiron --theme monokai  # just an example
```

FYI `--repo pyiron/pyiron` dictates the MyBinder repository to which the notebooks will be linked.

**Comment by jan-janssen** [comment]
Maybe it is easier to first build the Jupyter book in a separate repository, then it is available as something like pyiron.org/book which allows everybody to preview the changes. And then we can think about how to integrate it with read the docs and the rest of the pyiron documentation later.

**Comment by jan-janssen** [comment]
I close this pull request for now in the favour of https://github.com/pyiron/pyiron_documentation feel free to reopen it later.

**Pull request closed without merging**
