### PR TITLE
Unittests

### PR DESCRIPTION
**Pull request by samwaseda**
Added a few unittests

### CODE REVIEW

**Comment by samwaseda** [comment]
XD

**Comment by jan-janssen** [comment]
There seems to be an issue with Python 2.7: 

```
======================================================================
1904ERROR: test_get_equivalent_voronoi_vertices (atomistics.structure.test_atoms.TestAtoms)
1905----------------------------------------------------------------------
1906Traceback (most recent call last):
1907  File "/Users/travis/build/pyiron/pyiron/tests/atomistics/structure/test_atoms.py", line 471, in test_get_equivalent_voronoi_vertices
1908    vert = basis.get_equivalent_voronoi_vertices()
1909  File "pyiron/atomistics/structure/atoms.py", line 2026, in get_equivalent_voronoi_vertices
1910    _, box_copy = self._get_voronoi_vertices(minimum_dist = minimum_dist)
1911  File "pyiron/atomistics/structure/atoms.py", line 2005, in _get_voronoi_vertices
1912    while len(neigh.indices.flatten()[neigh.distances.flatten()<minimum_dist])!=0:
1913AttributeError: 'list' object has no attribute 'flatten'
1914
1915----------------------------------------------------------------------
```

**Comment by samwaseda** [comment]
> There seems to be an issue with Python 2.7:
> 
> ```
> ======================================================================
> 1904ERROR: test_get_equivalent_voronoi_vertices (atomistics.structure.test_atoms.TestAtoms)
> 1905----------------------------------------------------------------------
> 1906Traceback (most recent call last):
> 1907  File "/Users/travis/build/pyiron/pyiron/tests/atomistics/structure/test_atoms.py", line 471, in test_get_equivalent_voronoi_vertices
> 1908    vert = basis.get_equivalent_voronoi_vertices()
> 1909  File "pyiron/atomistics/structure/atoms.py", line 2026, in get_equivalent_voronoi_vertices
> 1910    _, box_copy = self._get_voronoi_vertices(minimum_dist = minimum_dist)
> 1911  File "pyiron/atomistics/structure/atoms.py", line 2005, in _get_voronoi_vertices
> 1912    while len(neigh.indices.flatten()[neigh.distances.flatten()<minimum_dist])!=0:
> 1913AttributeError: 'list' object has no attribute 'flatten'
> 1914
> 1915----------------------------------------------------------------------
> ```

So it's great that I wrote a unit test :)

**Comment by samwaseda** [comment]
Is this something I should have avoided?

**Pull request merged**
