### PR TITLE
small bugfix

### PR DESCRIPTION
**Pull request by samwaseda**

### CODE REVIEW

**Comment by samwaseda** [comment]
But frankly I'm not even sure if it's worth keeping `coarse_run`

**Comment by jan-janssen** [comment]
Should not `self._coarse_run` be defined in `__init__.py`

**Comment by samwaseda** [comment]
Since I usually don't like to have a lot of lines in `__init__`, I tend to use this structure, but I'm also fine with writing it in `__init__` in this case.

**Comment by jan-janssen** [comment]
Python recommends to be explicit rather than implicit https://stackoverflow.com/questions/40750584/this-inspection-detects-instance-attribute-definition-outside-init-method

**Comment by jan-janssen** [comment]
@samwaseda I guess you can merge this.

**Pull request merged**
