### PR TITLE
Disable resolving symbolic links

### PR DESCRIPTION
**Pull request by jan-janssen**
@SanderBorgmans Can you check if this resolves your issue with symbolic links?

### CODE REVIEW

**Comment by SanderBorgmans** [comment]
@jan-janssen Hi Jan, as I said during the skype call, this indeed solves the issue that the path on the node itself is altered. However, relative paths remain relative, is this a problem? I'll do some testing and will send you a mail with my findings soon.

**Comment by jan-janssen** [comment]
@SanderBorgmans I only removed the `resolve` part, but kept the `absolut`, so to my understanding this should solve the issue.

**Comment by jan-janssen** [comment]
@SanderBorgmans Does this solve your issue with the absolute paths? If yes we can merge it into the master branch.

**Comment by SanderBorgmans** [comment]
@jan-janssen I think it does. But I won't be sure until Tuesday, I have another node reservation then.

**Pull request merged**
