### PR TITLE
small bugfix when set_repeat is applied after get_initial_magnetic_mo…

### PR DESCRIPTION
**Pull request by samwaseda**
…ments is called, i.e. with the first `set_array` it repeats correctly, but then the second `set_repeat` changes the order.

```
structure.set_repeat(2)
m = np.ones(len(structure))
m[job.structure.select_index('Ni')] = -1
structure.set_initial_magnetic_moments(m)
structure.set_repeat(2)
```

### CODE REVIEW

**Comment by jan-janssen** [comment]
This breaks the tests: 

```
2020-02-17T15:40:31.7101853Z ======================================================================
2020-02-17T15:40:31.7102138Z ERROR: setUpClass (sphinx.test_interactive.TestSphinx)
2020-02-17T15:40:31.7102868Z ----------------------------------------------------------------------
2020-02-17T15:40:31.7102990Z Traceback (most recent call last):
2020-02-17T15:40:31.7103075Z   File "/home/vsts/work/1/s/tests/sphinx/test_interactive.py", line 35, in setUpClass
2020-02-17T15:40:31.7103411Z     cls.sphinx.write_input()
2020-02-17T15:40:31.7103598Z   File "/home/vsts/work/1/s/pyiron/sphinx/base.py", line 657, in write_input
2020-02-17T15:40:31.7103697Z     self.input_writer.write_guess(
2020-02-17T15:40:31.7103778Z   File "/home/vsts/work/1/s/pyiron/sphinx/base.py", line 1265, in write_guess
2020-02-17T15:40:31.7103887Z     if np.any(self.structure.get_initial_magnetic_moments().flatten() != None):
2020-02-17T15:40:31.7104229Z AttributeError: 'SparseList' object has no attribute 'flatten'
2020-02-17T15:40:31.7104315Z 
2020-02-17T15:40:31.7104391Z ======================================================================
2020-02-17T15:40:31.7104497Z ERROR: test_vasp_import (table.test_datamining.TestDatamining)
2020-02-17T15:40:31.7104774Z ----------------------------------------------------------------------
2020-02-17T15:40:31.7104882Z Traceback (most recent call last):
2020-02-17T15:40:31.7104969Z   File "/home/vsts/work/1/s/tests/table/test_datamining.py", line 69, in test_vasp_import
2020-02-17T15:40:31.7105081Z     table.run()
2020-02-17T15:40:31.7105166Z   File "/home/vsts/work/1/s/pyiron/base/job/generic.py", line 668, in run
2020-02-17T15:40:31.7105261Z     self._run_if_new(debug=debug)
2020-02-17T15:40:31.7105342Z   File "/home/vsts/work/1/s/pyiron/base/job/generic.py", line 1312, in _run_if_new
2020-02-17T15:40:31.7105437Z     self.run()
2020-02-17T15:40:31.7105512Z   File "/home/vsts/work/1/s/pyiron/base/job/generic.py", line 670, in run
2020-02-17T15:40:31.7105606Z     que_id = self._run_if_created()
2020-02-17T15:40:31.7105847Z   File "/home/vsts/work/1/s/pyiron/base/job/generic.py", line 1329, in _run_if_created
2020-02-17T15:40:31.7105947Z     self.run_static()
2020-02-17T15:40:31.7106023Z   File "/home/vsts/work/1/s/pyiron/table/datamining.py", line 678, in run_static
2020-02-17T15:40:31.7106117Z     self.update_table()
2020-02-17T15:40:31.7106193Z   File "/home/vsts/work/1/s/pyiron/table/datamining.py", line 693, in update_table
2020-02-17T15:40:31.7106464Z     self._pyiron_table.create_table(
2020-02-17T15:40:31.7106552Z   File "/home/vsts/work/1/s/pyiron/table/datamining.py", line 312, in create_table
2020-02-17T15:40:31.7106816Z     df_new_ids = self._iterate_over_job_lst(
2020-02-17T15:40:31.7106914Z   File "/home/vsts/work/1/s/pyiron/table/datamining.py", line 492, in _iterate_over_job_lst
2020-02-17T15:40:31.7106996Z     diff_dict = self._apply_list_of_functions_on_job(
2020-02-17T15:40:31.7107093Z   File "/home/vsts/work/1/s/pyiron/table/datamining.py", line 479, in _apply_list_of_functions_on_job
2020-02-17T15:40:31.7107181Z     funct_dict = self._apply_function_on_job(funct, job)
2020-02-17T15:40:31.7107275Z   File "/home/vsts/work/1/s/pyiron/table/datamining.py", line 407, in _apply_function_on_job
2020-02-17T15:40:31.7107350Z     return funct(job)
2020-02-17T15:40:31.7107438Z   File "/home/vsts/work/1/s/pyiron/table/funct.py", line 246, in get_magnetic_structure
2020-02-17T15:40:31.7107511Z     if all(magmons == None):
2020-02-17T15:40:31.7107799Z TypeError: 'bool' object is not iterable
2020-02-17T15:40:31.7107864Z 
2020-02-17T15:40:31.7107951Z ======================================================================
2020-02-17T15:40:31.7108205Z FAIL: test_import (vasp.test_vasp_import.TestVaspImport)
2020-02-17T15:40:31.7108492Z ----------------------------------------------------------------------
2020-02-17T15:40:31.7108576Z Traceback (most recent call last):
2020-02-17T15:40:31.7108672Z   File "/home/vsts/work/1/s/tests/vasp/test_vasp_import.py", line 35, in test_import
2020-02-17T15:40:31.7108749Z     self.assertTrue(
2020-02-17T15:40:31.7108831Z AssertionError: False is not true
```

Which again highlights the importance of adding tests anyway - so please also add a test for this case.

**Comment by jan-janssen** [comment]
@samwaseda Can you add the new test again, so we can see if @FeLoch changes are compatible with your new test?

**Comment by FeLoch** [comment]
nothing happened here for a long time...

**Comment by jan-janssen** [comment]
@FeLoch and @samwaseda What is the status on this pull request? As far as I can see the change: 

```
- return np.array(list(self.spin.values()))
+ return np.asarray(self.spin.list())
```

That is fine with me, but it does not solve the original issue, right? Therefore my recommendation would be to close the pull request for now.

**Comment by FeLoch** [comment]
It will as far as I remember. I will check it in near future.

**Pull request merged**
