### PR TITLE
:zap: Using scientific notation

### PR DESCRIPTION
**Pull request by sudarsan-surendralal**

### CODE REVIEW

**Comment by Leimeroth** [comment]
This fixes the problem for me can we merge it?

**Comment by jan-janssen** [comment]
I guess the issue is that it does not fix https://github.com/pyiron/pyiron/issues/981

**Comment by Leimeroth** [comment]
Strange, I encountered exactly the same problem in some of my OUTCARs when I tried to import surface calculations

**Comment by sudarsan-surendralal** [comment]
> 
> 
> Strange, I encountered exactly the same problem in some of my OUTCARs when I tried to import surface calculations

If the new branch is able to parse these calculations now then issue https://github.com/pyiron/pyiron/issues/981 is also probably fixed in my opinion. Can you confirm this?

**Comment by Leimeroth** [comment]
The imported calculations had status aborted before, if I import them using your branch they have the status finished and the cell is saved correctly. My OUTCARs had the same problem with lines like this one: 0.000000000  0.000000000102.532989545

**Comment by sudarsan-surendralal** [comment]
> 
> 
> The imported calculations had status aborted before, if I import them using your branch they have the status finished and the cell is saved correctly. My OUTCARs had the same problem with lines like this one: 0.000000000 0.000000000102.532989545

Ok thanks! Since this is the exact same problem @sravankumarkb had, I think we can now close this issue!

**Pull request merged**
