### PR TITLE
Pipeline

### PR DESCRIPTION
**Pull request by jan-janssen**
@SanderBorgmans Can you try this branch? It should enable submitting pipeline jobs to the queue. Please initially try it with the example notebook. For me it worked with both interactive jobs as well as modal jobs.

### CODE REVIEW

**Comment by jan-janssen** [comment]
This also includes the changes from https://github.com/pyiron/pyiron/pull/842

**Comment by SanderBorgmans** [comment]
@jan-janssen it seems the issue was that the 'queue' mode was not taken into account. 
When adding:

```
if job.server.run_mode.queue:
                break
```

to the run_static() function in https://github.com/pyiron/pyiron/blob/0fb4c52b2defab9fa22eaf9314323343eafe6299/pyiron/base/master/flexible.py#L157-L182 similar to the non_modal mode, everything seems to be working as expected.

**Comment by jan-janssen** [comment]
@SanderBorgmans Sounds reasonable - Can you open a pull request for this? It seems like the runmode queue wasn't considered properly.

**Comment by jan-janssen** [comment]
I created a new pull request for this https://github.com/pyiron/pyiron/pull/863

**Pull request merged**
