### PR TITLE
file_name is not taken over by the child job anymore and path is not …

### PR DESCRIPTION
**Pull request by samwaseda**
…encapsulated

### CODE REVIEW

**Comment by samwaseda** [comment]
ok I see that for some reason `job_table` does not get updated anymore when the job is submitted.

**Comment by samwaseda** [comment]
Which line

**Comment by samwaseda** [comment]
Anyway I don't understand what `child_job.project_hdf5.file_name = parent_job.project_hdf5.file_name` is for

**Comment by jan-janssen** [comment]
If you do not want this functionality, maybe it is easier to simply overload the function in your class rather than changing it in this class, as this class is used by many other classes.

**Comment by samwaseda** [comment]
No, I close this one

**Pull request closed without merging**
