### PR TITLE
phonopy updated to circumvent all deprecation warnings

### PR DESCRIPTION
**Pull request by samwaseda**
For the user nothing changed.

### CODE REVIEW

**Comment by jan-janssen** [comment]
Do we have tests to validate the output is the same?

**Comment by samwaseda** [comment]
If you are talking about unit tests, I don't know. I tested it with @raynol-dsouza's notebook:
[QHA_thermal_expansion.ipynb.txt](https://github.com/pyiron/pyiron/files/4598566/QHA_thermal_expansion.ipynb.txt)

**Comment by samwaseda** [comment]
Can I merge this one?

**Comment by jan-janssen** [comment]
> Can I merge this one?

yes

**Pull request merged**
