### PR TITLE
Fix interactive mode for GPAW

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Comment by jan-janssen** [comment]
@samwaseda I have the feeling just like the example job https://github.com/pyiron/pyiron/pull/989 also the GPAW job was not updated when you changed the interactive interface to no longer require an interactive cache.

**Comment by samwaseda** [comment]
> @samwaseda I have the feeling just like the example job #989 also the GPAW job was not updated when you changed the interactive interface to no longer require an interactive cache.

Yes I should have done it at that time. I just didn’t know whether GPAW was fully operational or not, but from now on I’m better informed.

**Comment by jan-janssen** [comment]
[Binder](https://mybinder.org/v2/gh/pyiron/pyiron/master?filepath=gpaw_fixes)

**Comment by samwaseda** [comment]
Is there a particular reason that there's no unit test for this module at all?

**Comment by jan-janssen** [comment]
As this pull request is not adding any new functionality but rather just removing outdated code to fix a bug I created a separate pull request for the unit tests https://github.com/pyiron/pyiron/pull/1078 .

**Pull request merged**
