### PR TITLE
Pressure axis

### PR DESCRIPTION
**Pull request by Ahmed-Aslam**
Issue : Removing redundant axis from output/pressures. 
It is solved by converting list of array to array of proper dimensions.

### CODE REVIEW

**Comment by jan-janssen** [comment]
Try to do the conversion before writing to HDF5, just like it is done for the temperature: https://github.com/pyiron/pyiron/blob/pressure_axis/pyiron/lammps/base.py#L432

**Comment by liamhuber** [comment]
As Jan suggests, let's fix the problem at its source.

In principle there's nothing *wrong* with this solution, and it's very pragmatic. However, it covers over the problem by adding an extra line of code. For a small project where you need to move fast and get things done this is an excellent solution. For a large project which needs to be maintained by a whole team of people, it adds one more line of code that is slightly mysterious and needs to be researched and understood if anything goes wrong later. Better then to dig in and remove the problem to begin with :)

**Comment by liamhuber** [comment]
I was reminded today that this principle has a fancy software design name: [technical debt](https://en.wikipedia.org/wiki/Technical_debt)

**Comment by jan-janssen** [comment]
@samwaseda as far as I understand https://github.com/pyiron/pyiron/pull/270 this pull request is no longer required. Can we close this pull request?

**Pull request closed without merging**
