### PR TITLE
Inherit from PyironFactory

### PR DESCRIPTION
**Pull request by liamhuber**
Dependent on [pyiron/pyiron_base#83](https://github.com/pyiron/pyiron_base/pull/83)

### CODE REVIEW

**Comment by liamhuber** [comment]
Now that the pyiton_base dependency is on tag `0.1.30`, this should be ready for review.

**Comment by liamhuber** [comment]
@jan-janssen I want to re-run the tests but don't want to add any silly empty commits to do it [(as in SO results I found)](https://stackoverflow.com/questions/52408592/how-to-relaunch-github-check-without-pushing-new-commits) -- do we have a sneaky way to do this? I guess most/all the tests should pass now that the dependencies are updated.

**Comment by jan-janssen** [comment]
> @jan-janssen I want to re-run the tests but don't want to add any silly empty commits to do it [(as in SO results I found)](https://stackoverflow.com/questions/52408592/how-to-relaunch-github-check-without-pushing-new-commits) -- do we have a sneaky way to do this? I guess most/all the tests should pass now that the dependencies are updated.

I can rerun the tests by clicking on the failed test and then there is a run again button (not sure if it is available for everybody) but the empty commit is definitely the easiest way.

**Review by jan-janssen — APPROVED** [review]
Looks good to me

**Pull request merged**
