### PR TITLE
Update installation.rst

### PR DESCRIPTION
**Pull request by samwaseda**
There were comments coming from PMD project partners, saying it's difficult to understand what the examples here actually do. I removed the parts which are not related to the actual queueing system installation.

### CODE REVIEW

**Review by niklassiemer — COMMENTED** [review]
In general updating the commands is good! However, do we want to teach everyone not to think about potentials any more?

**Comment by samwaseda** [comment]
> In general updating the commands is good! However, do we want to teach everyone not to think about potentials any more?

I can also think of putting it in the comment. The point is that each unrelated line makes it more difficult to understand what this document tries to tell, so I have the feeling that anything unrelated we can remove should be removed.

**Review by ligerzero-ai — APPROVED** [review]
Lgtm

**Comment by niklassiemer** [comment]
> > In general updating the commands is good! However, do we want to teach everyone not to think about potentials any more?
> 
> I can also think of putting it in the comment. The point is that each unrelated line makes it more difficult to understand what this document tries to tell, so I have the feeling that anything unrelated we can remove should be removed.

Fair point! However, a comment that this code will raise a warning would be good such that new users are not confused...

**Pull request merged**
