### PR TITLE
Fix Lammps pressure

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Review by samwaseda — APPROVED** [review]
Looks good to me. I guess at some point we really have to create a very good unit test which tests all these problems related to LAMMPS rotation...

**Comment by liamhuber** [comment]
The code change looks great, but I have a nagging fear that it won't do what we want. I have this vague memory that triclinic cell shape changes didn't translate from the pyiron reference frame to Lammps' reference frame and back again without introducing errors. 

Have you actually tested this code, e.g. by applying zero pressure on two axes and strong pressure on the other one and making sure the resulting pyiron structures are what you'd think they should be? As @samwaseda says, what we really need is a thorough test suite on this rotation matrix stuff.

**Comment by jan-janssen** [comment]
I tried: 
```
job.calc_minimize(pressure=0.0)
```
Previously this did not work for triclinic cells.

**Comment by liamhuber** [comment]
I have to reject this PR; under certain input it silently gives incorrect output.

I don't understand everything that's going on, but I will reiterate that it has to do with rotating the cell from the pyiron reference frame to the lammps reference frame. In this case, a zero-pressure test is insufficient because a*0=0 regardless of whether or not we correctly rotated a. 

The error message given in the master branch trying to run a triclinic cell with scalar pressure is very nearly the height of my understanding. My tests below have given an additional piece of insight: trying to run *either* a triclinic *or cubic* cell while specifying all six elements causes lammps to complain that you can't specify the off-diagonal pressure tensor components in a **non-triclinic** box. So whatever branch of the source code logic is dealing with this case needs some attention paid to the reference frame rotations.

I don't know the details of how to make this work good, but the master branch behaviour stops the user from doing anything bad. This branch seems to work only in the special case of zero pressure, and for non-zero pressure *definitely* gives totally the wrong results.

Abandon hope, all ye who attempt geometry 😭 

# Behaviour verification

Input:
```python
from pyiron import Project
pr = Project('scratch')
pr.remove_jobs_silently(recursive=True)
job = pr.create_job(pr.job_type.Lammps, 'lmp_pressure_test')
job.structure = pr.create_ase_bulk('Al', cubic=cubic)
job.potential = 'Al_Mg_eam_fs'  #job.list_potentials()[0]
job.calc_minimize(pressure=pressure)
job.run()

print(job.get_structure(0).cell.array)
print(job.get_structure(-1).cell.array)
print(np.linalg.norm(job.get_structure(-1).cell.array, axis=0))
```

## Master branch

Output with `pressure=0`, `cubic=True`: **Fine**
```python
[[4.05000000e+00 2.47990977e-16 2.47990977e-16]
 [0.00000000e+00 4.05000000e+00 2.47990977e-16]
 [0.00000000e+00 0.00000000e+00 4.05000000e+00]]

[[4.04527054e+00 2.47701381e-16 2.47701381e-16]
 [0.00000000e+00 4.04527054e+00 2.47701381e-16]
 [0.00000000e+00 0.00000000e+00 4.04527054e+00]]

[4.04527054 4.04527054 4.04527054]
```

Output with `pressure=1`, `cubic=True`: **Fine**
```python
[[4.05000000e+00 2.47990977e-16 2.47990977e-16]
 [0.00000000e+00 4.05000000e+00 2.47990977e-16]
 [0.00000000e+00 0.00000000e+00 4.05000000e+00]]

[[3.50959243e+00 2.14900557e-16 2.14900557e-16]
 [0.00000000e+00 3.50959243e+00 2.14900557e-16]
 [0.00000000e+00 0.00000000e+00 3.50959243e+00]]

[3.50959243 3.50959243 3.50959243]
```

Output with `pressure=0`, `cubic=False`: **Fails cleanly**
```python
ValueError: Cells which are not orthorhombic or rectangular are incompatible with Lammps constant pressure calculations unless the entire pressure tensor is defined.The reason is that Lammps demands such cells be represented with an upper-triangular unit cell, thus a rotation between Lammps and pyiron coordinateframes is required; it is not possible to rotate the pressure tensor if any of its components is None.
```

Output with `pressure=1`, `cubic=False`: **Fails cleanly**
```python
ValueError: ...
```

Output with `pressure=[1, 1, 1, 0, 0, 0]`, `cubic=False`: **Fails messily**
Fails with Lammps error 
```
ERROR: Can not specify Pxy/Pxz/Pyz in fix box/relax with non-triclinic box
Last command: fix ensemble all box/relax x 100000000.0 y 100000000.0 z 100000000.0 xy 0.0 xz 0.0 yz 0.0 couple none
```

Output with `pressure=6*[0]`, `cubic=True`: **Fails messily**
```
ERROR...
```

## This branch

Output with `pressure=0`, `cubic=True`: **Fine**
```python
[[4.05000000e+00 2.47990977e-16 2.47990977e-16]
 [0.00000000e+00 4.05000000e+00 2.47990977e-16]
 [0.00000000e+00 0.00000000e+00 4.05000000e+00]]

[[4.04527054e+00 2.47701381e-16 2.47701381e-16]
 [0.00000000e+00 4.04527054e+00 2.47701381e-16]
 [0.00000000e+00 0.00000000e+00 4.04527054e+00]]

[4.04527054 4.04527054 4.04527054]
```

Output with `pressure=1`, `cubic=True`: **Fine**
```python
[[4.05000000e+00 2.47990977e-16 2.47990977e-16]
 [0.00000000e+00 4.05000000e+00 2.47990977e-16]
 [0.00000000e+00 0.00000000e+00 4.05000000e+00]]

[[3.50959243e+00 2.14900557e-16 2.14900557e-16]
 [0.00000000e+00 3.50959243e+00 2.14900557e-16]
 [0.00000000e+00 0.00000000e+00 3.50959243e+00]]

[3.50959243 3.50959243 3.50959243]
```

Output with `pressure=0`, `cubic=False`: **Fine**
```python
[[ 3.48077271e-16  2.02500000e+00  2.02500000e+00]
 [ 2.02500000e+00  2.96989100e-11  2.02500000e+00]
 [ 2.02500000e+00  2.02500000e+00 -2.80332953e-11]]

[[ 3.47670590e-16  2.02263406e+00  2.02263406e+00]
 [ 2.02263524e+00  1.49601234e-05  2.02265020e+00]
 [ 2.02264531e+00  2.02262377e+00 -2.77509277e-07]]

[2.8604453  2.86042924 2.86044793]
```

Output with `pressure=1`, `cubic=False`: **BORKEN -- NO WARNING**
```python
[[ 3.48077271e-16  2.02500000e+00  2.02500000e+00]
 [ 2.02500000e+00  2.96989100e-11  2.02500000e+00]
 [ 2.02500000e+00  2.02500000e+00 -2.80332953e-11]]

[[ 2.31016962e-16  1.34398131e+00  1.34398131e+00]
 [ 1.94180406e+00 -1.35237314e+00  5.89430919e-01]
 [ 1.80213247e+00  1.95541493e+00 -4.72234538e-01]]

[2.64920449 2.73108887 1.54166145]
```

**Review by liamhuber — CHANGES_REQUESTED** [review]
The part of the code touched here looks fine, but this whole branch of the logic is (somewhere else?) implemented incorrectly. These changes allow the user to silently get the wrong output, so I can't accept the PR. Cf. comment for details.

**Comment by jan-janssen** [comment]
@liamhuber As @yury-lysogorskiy posted in https://github.com/pyiron/pyiron/issues/1016 the major issue is that `pressure=0.0` fails for the master branch with triclinic cells.

**Comment by jan-janssen** [comment]
Previously we had `calc_minimize(pressure=0.0)` which for LAMMPS equals `fix 1 all box/relax iso 0.0` I do not understand why this was removed in the first place.

**Comment by liamhuber** [comment]
I probably killed the `fix 1 all box/relax iso 0.0` when I was last working on this code, sorry.

I have no objection to the `fix 1 all box/relax iso 0.0` functionality being added back for triclinic cells, although from Yury's "**full relaxation**" I interpreted that he wanted anisotropic relaxation.

Regardless, this pull is still no good because triclinic cells with non-zero pressure *silently* be crazy. A messy-but-acceptable solution (IMO) would be to patch this PR so that it does what it does *only* when the pressure is exactly zero, as this is a special case where (I don't think???) our rotation problems have a chance to mess anything up.

Overall non-isotropic relaxation in Lammps is simply not a thing we can say we do safely right now. I don't think there's anything wrong with the PR itself! Rather my understand is that the PR unlocks dangerous interactions with bad structure conversion code.

[These](https://github.com/pyiron/pyiron/pull/496/files) [seem](https://github.com/pyiron/pyiron/pull/463/files) like the most related pull requests, but I couldn't see where the `box/relax iso` got cut, so maybe there's another one out there that's relevant. Unfortunately, I won't be able to dig into this at the moment.

**Comment by samwaseda** [comment]
> I probably killed the `fix 1 all box/relax iso 0.0` when I was last working on this code, sorry.

It was actually me, when I was calculating Poisson's coefficients by fixing the box size in one particular direction...

**Review by liamhuber — APPROVED** [review]
It still feels sketchy to carefully allow the one edge case that works, but I don't have any specific objections anymore ;)

**Comment by liamhuber** [comment]
> > I probably killed the `fix 1 all box/relax iso 0.0` when I was last working on this code, sorry.
> 
> It was actually me, when I was calculating Poisson's coefficients by fixing the box size in one particular direction...

busted

😜

**Pull request merged**
