### PR TITLE
Surface pbc

### PR DESCRIPTION
**Pull request by sudarsan-surendralal**
Adding options to set the pbc when calling structures

### CODE REVIEW

**Comment by jan-janssen** [comment]
I was just thinking about the create_structure and create_surface functions to be moved to the structure class. And then import them in the project as well as in pyiron __init__ this would allow users to import these functions without the need of creating a project.

**Comment by jan-janssen** [comment]
Can you do the same for `create_structure()` and `create_ase_bulk()` ? And add all three functions in `pyiron/__init__.py`.

**Comment by sudarsan-surendralal** [comment]
I made the changes but, I'm getting the following error when I test locally (not here in Travis CI)

`AttributeError: module 'pyiron.atomistics.structure' has no attribute 'atoms'`

Also `create_structure` simply calls `CrystalStructure`

**Comment by jan-janssen** [comment]
That is because you import `pyironase` before the `Atoms` class is defined and in `pyironase` The `atoms` class is imported from `atoms` causing an infinite loop. Most likely we have to move these functions to a separate file.

**Comment by sudarsan-surendralal** [comment]
@jan-janssen let me know if you need more changes

**Comment by jan-janssen** [comment]
I do not like the import in the functions - that is not PEP8. My suggestion would be to move the functions to a separate module rather than the Atoms class.

**Comment by sudarsan-surendralal** [comment]
> 
> 
> Looks good to me - Can you present it in next weeks pyiron meeting? Just a quick notebook should be fine.

Sure!

**Pull request merged**
