### PR TITLE
Update pyscal interface

### PR DESCRIPTION
**Pull request by jan-janssen**
https://github.com/srmnitc/pyscal/issues/36

### CODE REVIEW

**Comment by jan-janssen** [comment]
We still need to add support for triclinic cells:

> Triclinic boxes can also be read in by providing the is_triclinic keyword as True for read_inputfile.

**Comment by srmnitc** [comment]
@jan-janssen I could contribute to the pyscal interface if it helps!

**Comment by jan-janssen** [comment]
@srmnitc that would be great. Do you already have an interface to identify if the cell is triclinic or not? Otherwise we can use the ase routines: 

```
from ase.calculators.lammps.coordinatetransform import Prism
sys.read_inputfile(aseobj, format='ase', is_triclinic=not Prism(structure.cell, digits=15).is_skewed())
```

**Comment by jan-janssen** [comment]
I guess we should also add some unit tests for pyscal to be sure it works with both normal and triclinic cells.

**Comment by srmnitc** [comment]
@jan-janssen I guess I could port some unit tests that pyscal has. I will work on this a little later this week.

**Comment by jan-janssen** [comment]
I still have to add `sklearn` to the dependencies.

**Comment by jan-janssen** [comment]
There seems to be some issue with the tests: 


```
2020-01-28T06:45:44.6940185Z .
2020-01-28T06:45:44.6941245Z ======================================================================
2020-01-28T06:45:44.6942033Z FAIL: test_bcc_cubic (atomistics.structure.test_pyscal.TestAtoms)
2020-01-28T06:45:44.6943507Z ----------------------------------------------------------------------
2020-01-28T06:45:44.6944033Z Traceback (most recent call last):
2020-01-28T06:45:44.6944504Z   File "/home/vsts/work/1/s/tests/atomistics/structure/test_pyscal.py", line 24, in test_bcc_cubic
2020-01-28T06:45:44.6944972Z     self.assertEqual(sum(ind), 53)
2020-01-28T06:45:44.6945381Z AssertionError: 29 != 53
2020-01-28T06:45:44.6945757Z 
2020-01-28T06:45:44.6950270Z ======================================================================
2020-01-28T06:45:44.6950564Z FAIL: test_bcc_triclinic (atomistics.structure.test_pyscal.TestAtoms)
2020-01-28T06:45:44.6951247Z ----------------------------------------------------------------------
2020-01-28T06:45:44.6951510Z Traceback (most recent call last):
2020-01-28T06:45:44.6951931Z   File "/home/vsts/work/1/s/tests/atomistics/structure/test_pyscal.py", line 36, in test_bcc_triclinic
2020-01-28T06:45:44.6952149Z     self.assertEqual(sum(sysq[0]), 2.1642207792631947)
2020-01-28T06:45:44.6952339Z AssertionError: 1.739252574773128 != 2.1642207792631947
2020-01-28T06:45:44.6952445Z 
2020-01-28T06:45:44.6952595Z ======================================================================
2020-01-28T06:45:44.6952789Z FAIL: test_fcc_cubic (atomistics.structure.test_pyscal.TestAtoms)
2020-01-28T06:45:44.6953368Z ----------------------------------------------------------------------
2020-01-28T06:45:44.6953539Z Traceback (most recent call last):
2020-01-28T06:45:44.6953736Z   File "/home/vsts/work/1/s/tests/atomistics/structure/test_pyscal.py", line 49, in test_fcc_cubic
2020-01-28T06:45:44.6953924Z     self.assertEqual(sum(sysq[0]), 20.621590627301256)
2020-01-28T06:45:44.6954104Z AssertionError: 20.621590627301252 != 20.621590627301256
2020-01-28T06:45:44.6954225Z 
2020-01-28T06:45:44.6954370Z ======================================================================
2020-01-28T06:45:44.6954565Z FAIL: test_fcc_triclinic (atomistics.structure.test_pyscal.TestAtoms)
2020-01-28T06:45:44.6955127Z ----------------------------------------------------------------------
2020-01-28T06:45:44.6955294Z Traceback (most recent call last):
2020-01-28T06:45:44.6955490Z   File "/home/vsts/work/1/s/tests/atomistics/structure/test_pyscal.py", line 62, in test_fcc_triclinic
2020-01-28T06:45:44.6955680Z     self.assertEqual(sum(sysq[0]), 4.393254735603798)
2020-01-28T06:45:44.6955860Z AssertionError: 4.719620556043611 != 4.393254735603798
2020-01-28T06:45:44.6955962Z 
2020-01-28T06:45:44.6956106Z ======================================================================
2020-01-28T06:45:44.6956295Z FAIL: test_hcp_triclinic (atomistics.structure.test_pyscal.TestAtoms)
2020-01-28T06:45:44.6956823Z ----------------------------------------------------------------------
2020-01-28T06:45:44.6957020Z Traceback (most recent call last):
2020-01-28T06:45:44.6957216Z   File "/home/vsts/work/1/s/tests/atomistics/structure/test_pyscal.py", line 75, in test_hcp_triclinic
2020-01-28T06:45:44.6957414Z     self.assertEqual(sum(sysq[0]), 10.116252659874087)
2020-01-28T06:45:44.6957594Z AssertionError: 9.401479091803367 != 10.116252659874087
2020-01-28T06:45:44.6957700Z 
2020-01-28T06:45:44.6958195Z ----------------------------------------------------------------------
```

**Comment by srmnitc** [comment]
@jan-janssen couple of questions - in the first case `test_bcc_cubic (atomistics.structure.test_pyscal.TestAtoms)`, the clustering algorithm uses 2 clusters - but there is only one. Maybe this is the source of the mismatch? 

For the tests of q_4 values with triclinic and cubic cell - what is the source of the reference values - irrespective of the cubic/triclinic structure, the q value of an atom should be the same. The sum differs of course based on the number of  atoms. I can confirm both triclinic and cubic cells gives the same results. I used the ase bulk to create the structures. Code bit is given below-

```
import pyscal.core as pc
from ase.build import bulk

a1 = bulk('Fe', cubic=True)
a2 = a1.repeat([3,3,3])
sysc = pc.System()
sysc.read_inputfile(a2, format='ase')
sysc.find_neighbors(method='cutoff', cutoff=3.5)
sysc.calculate_q([4,6], averaged=True)
sysqc = sysc.get_qvals([4,6], averaged=True)
```
I tried the same above with `cubic=False` and I am able to replicate the results.

**Comment by jan-janssen** [comment]
@srmnitc You are completely right - two clusters makes no sense - I now modified the tests to return only one cluster, that should be fine. I guess the important part for me is that we test the integration with pyiron, ase and pascal to be sure the APIs are compatible even when packages change in future.

**Pull request merged**
