### PR TITLE
Try to fix https://github.com/pyiron/pyiron/issues/117

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Comment by jan-janssen** [comment]
@sudarsan-surendralal Can you test this fix?

**Comment by sudarsan-surendralal** [comment]
I used exception handling instead of if https://github.com/pyiron/pyiron/pull/118/commits/14d3a87d6d7e0077a26134a15b85e8e7c988c44d. Added a unittest as well

**Comment by jan-janssen** [comment]
@sudarsan-surendralal I guess exception handling is not so nice, if we can identify the error before hand we should not need the exception.

**Comment by jan-janssen** [comment]
It should be because the number is larger than 99999

**Comment by jan-janssen** [comment]
Is OUTCAR_9 just a copy of OUTCAR_1 with the 'Broyden mixing:' line replaced?

**Comment by jan-janssen** [comment]
For the job that crashed can you please copy the following lines: 

```
 Broyden mixing: mesh for mixing (old mesh)
   NGX =  9   NGY =  9   NGZ =  9
  (NGX  = 40   NGY  = 40   NGZ  = 40)
  gives a total of    ****** points 
```

**Pull request merged**
