### PR TITLE
Euler

### PR DESCRIPTION
**Pull request by samwaseda**
Following [Jan's comment](https://github.com/pyiron/pyiron/pull/337)

### CODE REVIEW

**Comment by samwaseda** [comment]
... and `get_center_of_mass` was added since the function itself was called in `rotate` and `rotate_euler` but didn't exist

**Comment by samwaseda** [comment]
There's no coverall result?

**Comment by jan-janssen** [comment]
Their website is down at the moment https://coveralls.io

**Comment by jan-janssen** [comment]
In the meantime we can use https://app.codacy.com/app/pyiron-runner/pyiron/file/37059292200/coverage?bid=9358312&fileBranchId=9358312

**Pull request merged**
