### PR TITLE
deleted get_equivalent_atoms 

### PR DESCRIPTION
**Pull request by samwaseda**
I'm not even sure if anyone has ever used this function, but I don't think it was working correctly and without DocString it's not even clear what's the difference between this one and `get_symmetry()` (although I guess there was no difference).

### CODE REVIEW

**Comment by samwaseda** [comment]
It's possible that I implemented the function though...

**Comment by jan-janssen** [comment]
The function is over three years old, which makes it a bit difficult to track back the origin https://gitlab.mpcdf.mpg.de/pyiron/pyiron/-/blob/38f03ec7e55659d06004bab14257e836845ad096/PyIron/Structure/Atoms.py#L1468 

@sudarsan-surendralal Do you remember if it is used for the water calculation?

**Comment by jan-janssen** [comment]
In addition it is no an ASE function, so I am open to removing it https://gitlab.com/search?utf8=✓&snippets=&scope=&repository_ref=&search=get_equivalent_atoms&project_id=470007

**Comment by jan-janssen** [comment]
Most likely the easiest way is to quickly discuss it in the next pyiron meeting.

**Comment by samwaseda** [comment]
> The function is over three years old, which makes it a bit difficult to track back the origin https://gitlab.mpcdf.mpg.de/pyiron/pyiron/-/blob/38f03ec7e55659d06004bab14257e836845ad096/PyIron/Structure/Atoms.py#L1468
> 
> @sudarsan-surendralal Do you remember if it is used for the water calculation?

Ok I first thought I implemented it two years ago when I started doing SSA, but probably it wasn't me in the end. Then I guess Jörg was the one who implemented it ... ?

**Comment by pmrv** [comment]
> The function is over three years old, which makes it a bit difficult to track back the origin https://gitlab.mpcdf.mpg.de/pyiron/pyiron/-/blob/38f03ec7e55659d06004bab14257e836845ad096/PyIron/Structure/Atoms.py#L1468
> 
> @sudarsan-surendralal Do you remember if it is used for the water calculation?

iirc, it's used in one of the handbook notebooks, would be easy for me to update though, if we merge this.

**Comment by samwaseda** [comment]
> Most likely the easiest way is to quickly discuss it in the next pyiron meeting.

Maybe it's also time to separate various functionalities inside `atoms.py`, since it has close to 5,000 lines and does everything from box creation to structure analysis.

**Comment by sudarsan-surendralal** [comment]
> 
> 
> The function is over three years old, which makes it a bit difficult to track back the origin https://gitlab.mpcdf.mpg.de/pyiron/pyiron/-/blob/38f03ec7e55659d06004bab14257e836845ad096/PyIron/Structure/Atoms.py#L1468
> 
> @sudarsan-surendralal Do you remember if it is used for the water calculation?

No I think only Jörg knows what this does actually! Not sure if any of us use it

**Pull request merged**
