### PR TITLE
require user input in `remove_jobs` + create `remove_jobs_silently`

### PR DESCRIPTION
**Pull request by ashtonmv**
As discussed in #843 and in today's meeting, I built a user input call into `Project.remove_jobs()` to confirm the removal:

```python
def remove_jobs(self, recursive=False):
    """
    Remove all jobs in the current project and in all subprojects if recursive=True is selected - see also
    remove_job().

    For safety, the user is asked via input() to confirm the removal. To bypass this
    interactive interruption, use `remove_jobs_silently()`.

    Args:
        recursive (bool): [True/False] delete all jobs in all subprojects - default=False
    """
    if not isinstance(recursive, bool):
        raise ValueError('recursive must be a boolean')
    if not self.view_mode:
        confirmed = None
        while confirmed not in ["y", "n"]:
            if confirmed is None:
                confirmed = input(
                    "Are you sure you want to delete all jobs from "
                    + f"'{self.base_name}'? y/(n)"
                    ).lower()
            else:
                confirmed = input(
                    "Invalid response. Please enter 'y' (yes) or 'n' (no): "
                    ).lower()
        if confirmed == "y":
            # proceed to delete the jobs
            for job_id in self.get_job_ids(recursive=recursive):
                if job_id not in self.get_job_ids(recursive=recursive):
                    continue
                else:
                    try:
                        self.remove_job(job_specifier=job_id)
                        s.logger.debug("Remove job with ID {0} ".format(job_id))
                    except (IndexError, Exception):
                        s.logger.debug(
                            "Could not remove job with ID {0} ".format(job_id)
                        )
        else:
            print(f"No jobs removed from '{self.base_name}'.")
    else:
        raise EnvironmentError("copy_to: is not available in Viewermode !")
```

To leave the tests and notebooks unaffected, I replaced their calls to `remove_jobs` with `remove_jobs_silently`, which does exactly what the original function did.

I added a test for the new "interactive" `remove_jobs` in test_project.py.

### CODE REVIEW

**Review by jan-janssen — APPROVED** [review]
Looks good to me - feel free to merge it once the tests passed

**Comment by ashtonmv** [comment]
I'm not sure what's happening with the coverage report. The 849 lines that "lost coverage" don't seem to have anything to do with what I changed, but I of course don't want to decrease the master branch's coverage. How strictly are we adhering to that build status?

**Comment by sudarsan-surendralal** [comment]
> 
> 
> I'm not sure what's happening with the coverage report. The 849 lines that "lost coverage" don't seem to have anything to do with what I changed, but I of course don't want to decrease the master branch's coverage. How strictly are we adhering to that build status?

My guess is that it's because of some examples (Murnaghan examples I think) that covers areas of code depending on random initialization which could cause the decrease. @jan-janssen am I right?

**Comment by jan-janssen** [comment]
The issue is that we run some tests for the non modal mode, which are executed in the background. As the order of the tests is a bit random the coverage is some times a bit fluctuating.

**Pull request merged**
