### PR TITLE
Fix copy_to()

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Comment by sravankumarkb** [comment]
@jan-janssen 
Should I update my pyiron and execute the example notebook again?
https://github.com/pyiron/pyiron-meeting-mpie/blob/master/handbook/6-file-and-job-management/6-3-rename-move-copy/project.ipynb

**Comment by sravankumarkb** [comment]
So, I updated my local pyiron and ran the example, I have the same errors with the extra entries in the job_table like I showed in the images previously. 

I checked the /software/pyiron/pyiron/base/project/generic.py file to make sure that the new lines in the code are also present on my local file.

```
raise NotImplementedError("Implement if needed, e.g. for [:]")
```
```
                except ValueError:
                    return self._get_item_helper(
```
and so on. 
So, I think I have updated my local pyiron correctly and also loading my local pyiron correctly

```
import pyiron
pyiron.__file__
```
```
'/u/skanchar/software/pyiron/pyiron/__init__.py'
```

**Comment by jan-janssen** [comment]
For me it fixed the issue. So please navigate to the directory on the command line and check `git status`. You can use:
```
git fetch
git checkout copy_to_fix 
```
to switch to this branch.

**Comment by sravankumarkb** [comment]
Thanks @jan-janssen 
It is working for me as well after switching to the branch. Now my folders are structured much better.

**Comment by sravankumarkb** [comment]
Oops, I am not sure if I was supposed to close the issue. Please feel free to reopen this if it is required to merge the commits.

**Comment by jan-janssen** [comment]
Perfect - I merge the changes to the master branch. So you can switch now back to the master using: 
```
git checkout master
git pull
```

**Pull request merged**
