### PR TITLE
K mesh ang

### PR DESCRIPTION
**Pull request by sudarsan-surendralal**
Continuation of the already merged PR https://github.com/pyiron/pyiron/pull/1208

### CODE REVIEW

**Review by samwaseda — APPROVED** [review]
To be honest I don't really understand what it does, but if it works I have nothing against it.

**Comment by yury-lysogorskiy** [comment]
@sudarsan-surendralal , why do you remove `modify_kpoints()` ? It seems for me, that it wouldn't help...

**Comment by sudarsan-surendralal** [comment]
> 
> 
> @sudarsan-surendralal , why do you remove `modify_kpoints()` ? It seems for me, that it wouldn't help...

I didn't remove `modify_kpoints()` instead I shifted it to `save()` which is called before `to_hdf()`, and `write_input()` which fixes the issue. I tested this with the following Murnaghan job where the kpoints change with supercell volume

```
from pyiron import Project
import numpy as np
pr = Project("K_mesh")
job = pr.create_job(pr.job_type.Sphinx, "sphinx_ref")
job.structure = pr.create_ase_bulk("Al")
job.k_mesh_spacing = 0.25
murn = job.create_job(pr.job_type.Murnaghan, "murn")
murn.input["vol_range"] = 0.2
murn.run()
[job.input.KpointFolding for job in murn.iter_jobs()]

>>> [Group([12, 12, 12]),
 Group([11, 11, 11]),
 Group([11, 11, 11]),
 Group([11, 11, 11]),
 Group([11, 11, 11]),
 Group([11, 11, 11]),
 Group([11, 11, 11]),
 Group([10, 10, 10]),
 Group([10, 10, 10]),
 Group([10, 10, 10]),
 Group([10, 10, 10])]

```

**Comment by yury-lysogorskiy** [comment]
Just for improving my understanding, what is a basic call chain starting from `vasp_job.run()`? Which method is calling `.save()`?

**Comment by sudarsan-surendralal** [comment]
>
> 
> Just for improving my understanding, what is a basic call chain starting from `vasp_job.run()`? Which method is calling `.save()`?


Off the top of my head, I think it's `run --> _run_if_new --> validate --> save (to_hdf called within this function)  --> run -->write_input`.

**Review by yury-lysogorskiy — COMMENTED** [review]
Ok, hope that would work on the production code. I'll try to follow the same solution for FHIaims

**Pull request merged**
