### PR TITLE
NMA module added to latest master from hpc_ugent

### PR DESCRIPTION
**Pull request by SanderBorgmans**

### CODE REVIEW

**Comment by jan-janssen** [comment]
I extended the requirements to include `molmod` and `tamkin`.

**Comment by jan-janssen** [comment]
It seems like there are issues to resolve the dependencies on windows - AppVeyor tests fail.

**Comment by jan-janssen** [comment]
Python 3.8 fails - still waiting for https://github.com/molmod/molmod/pull/33

**Comment by jan-janssen** [comment]
There seems to be an issue resolving the dependencies on Mac Os X as well.

**Comment by jan-janssen** [comment]
@SanderBorgmans I was able to resolve most of the dependencies, now there are only two issues left:

- molmod is not yet python 3.8 ready 
- quickff is not yet available via pip

Can you take care of these?

**Comment by SanderBorgmans** [comment]
> @SanderBorgmans I was able to resolve most of the dependencies, now there are only two issues left:
> 
> * molmod is not yet python 3.8 ready
> * quickff is not yet available via pip
> 
> Can you take care of these?

I will contact those responsible for the molmod and quickff packages.

**Comment by SanderBorgmans** [comment]
> > @SanderBorgmans I was able to resolve most of the dependencies, now there are only two issues left:
> > 
> > * molmod is not yet python 3.8 ready
> > * quickff is not yet available via pip
> > 
> > Can you take care of these?
> 
> I will contact those responsible for the molmod and quickff packages.

@jan-janssen Normally Louis would take care of this, but with the outbreak of the coronavirus, things are quite hectic and all courses need (re)organisation. Is this urgent? Otherwise I will try to do this myself.

**Comment by jan-janssen** [comment]
From my perspective it is not urgent, I just want to get all the codes on one level before we merge the changes to the master branch.

**Comment by SanderBorgmans** [comment]
@jan-janssen I don't think I can write significant unit tests here, as the main functions (animate and plot) are there to produce some output in the jupyter notebook. What do you think? Maybe a single test for the init?

**Comment by jan-janssen** [comment]
@SanderBorgmans From my perspective it is also fine if we merge the changes like this. 

As far as I can see, we can now merge: 

- https://github.com/pyiron/pyiron/pull/548
- https://github.com/pyiron/pyiron/pull/549
- https://github.com/pyiron/pyiron/pull/550
- https://github.com/pyiron/pyiron/pull/554

**Comment by SanderBorgmans** [comment]
> @SanderBorgmans From my perspective it is also fine if we merge the changes like this.
> 
> As far as I can see, we can now merge:
> 
> * #548
> * #549
> * #550
> * #554

@jan-janssen I plan to add some minor unit tests to the QuickFF module today #550 
The others shoud be fine!

**Pull request merged**
