### PR TITLE
update JOB_CLASS_DICT automatically via metaclass

### PR DESCRIPTION
**Pull request by pmrv**
Since we talked about this a while ago and it came up again in #703 (though not as the cause).  I spent some time digging in the [python docs](https://docs.python.org/3.8/reference/datamodel.html#object.__init_subclass__) about subclassing.

With this `JOB_CLASS_DICT` is automatically updated when `JobCore` is subclassed independently from where, so we don't have to manually maintain it and without having to search for subclasses at runtime (as previously).  A downside is that all job types actually need to be imported on importing pyiron (hence the new imports in `pyiron.__init__`) to show up in the auto-completion. But since we want to modularize pyiron in the midterm, it might be ok.   Metaclasses are a bit scary, but hope the comments make it clear how it works.
 
I'm not sure how it interacts with loading custom jobs, but my understanding was that `JOB_CLASS_DICT` exists for the auto-completion only anyways.

### CODE REVIEW

**Comment by jan-janssen** [comment]
If I understand it correctly you load all classes before they are used, while the previous code only loads the classes when they are used. In addition classes like ParallelMaster are derived from GenericJob but are never used by the end user. Given these constraints I decided to specify the classes available for the user manually.

**Comment by pmrv** [comment]
Yes, it is necessary to import them now, before they show up.  But once we start splitting pyiron up, the user would have to import the sub-packages that they need anyways.

Fair point that this makes all subclasses show up, an alternative might to use a class decorator explicitly on all job types we want to offer for auto-completion
```python
def autocomplete(cls):
  from pyiron.job.jobtype import JOB_CLASS_DICT
  JOB_CLASS_DICT[cls.__name__] = cls.__module__

@autocomplete
class UserFacingJob(JobCore):
  pass
```

I'm not married to this PR though, I just saw `__init_subclass__` and thought it might be a good fit.

**Comment by jan-janssen** [comment]
Can you time both variants? From my feeling using static paths should be faster when importing pyiron, because we only import one class `from pyiron import Project` instead of 30+.

**Comment by pmrv** [comment]
```bash
time python -c "import pyiron"
```
takes 1.3 seconds on the master branch and 1.7 seconds on the meta branch.   The approach with the decorators is also 1.7 seconds.

**Comment by jan-janssen** [comment]
I looked at the memory usage: 
```
from guppy import hpy
h=hpy()
h.heap()
```
and afterwards:
```
import pyiron
h.heap()
```

First print for just python 29MB:
```
Partition of a set of 235100 objects. Total size = 28881936 bytes.
```

Current pyiron master branch 99MB:
``` 
Partition of a set of 713563 objects. Total size = 99259704 bytes.
```

This branch 128MB:
```
Partition of a set of 953148 objects. Total size = 128047875 bytes.
```

While I like meta programming, like the introduction of meta classes here, I am not sure if increasing out memory footprint by roughly 30% is worth it.

**Comment by pmrv** [comment]
I agree.  The additional memory consumption is only from having all job types immediately imported though, so maybe once we have a more modular pyiron this can be revisited.

**Comment by jan-janssen** [comment]
Yes, I agree. On a deeper level it is elegancy vs. efficiency and I do not have a general solution for this one. On the one hand ugly optimised code is hard to maintain, on the other hand elegant code is usually a bit slower. Therefore I would suggest to open this pull request again, so we can discuss this general principle in the next pyiron meeting and maybe come up with some kind of rule what level of tradeoff is reasonable.

**Pull request closed without merging**
