### PR TITLE
pyiron atoms changed to pbc when not specified

### PR DESCRIPTION
**Pull request by samwaseda**
I did this mainly because `get_structure()` was returning a non-periodic box

### CODE REVIEW

**Comment by pmrv** [comment]
I thought our consensus was to keep with the ASE default in the constructor and overrride `pbc` when our functions create `Atoms` objects.  Can we pass `pbc = True` when `get_structure()` makes a new Atoms object instead?

**Comment by samwaseda** [comment]
Ok I wasn't really sure about our `Atoms` class. I'm fine with changing it in `get_structure`

**Comment by jan-janssen** [comment]
@samwaseda Most likely we have to update this everywhere where `get_structure()` is defined.

**Comment by jan-janssen** [comment]
I found two similar issues https://github.com/pyiron/pyiron/pull/862 and https://github.com/pyiron/pyiron/pull/861

**Pull request merged**
