### PR TITLE
Sphinx tests

### PR DESCRIPTION
**Pull request by samwaseda**
A few tests added

### CODE REVIEW

**Comment by jan-janssen** [comment]
@samwaseda Can yew close this pull request? I guess @pmrv is working on this issue in https://github.com/pyiron/pyiron/pull/749

**Comment by samwaseda** [comment]
Actually my intention here was to update the test notebook, since as you might have noticed it only runs the jobs and does not check if the output is correct. Right now I'm waiting for @pmrv to finish his stuff to adapt this pull request. So I can't close this one.

**Comment by jan-janssen** [comment]
Maybe it makes sense to create a separate pull request for the updated notebook. In addition it would be nice to add an example with reload like https://github.com/pyiron/pyiron/pull/749#issuecomment-647034010 
```
from pyiron import Project
pr = Project('SPX_CHECK_ALL')
job = pr.create_job(pr.job_type.Sphinx, 'nonmodal2')
job.structure = pr.create_structure('Fe', 'bcc', a_Fe)
job.calc_static()
job._create_job_structure()
job_reload = pr.load(job.job_name)
job_reload.run()
```

**Comment by samwaseda** [comment]
> Maybe it makes sense to create a separate pull request for the updated notebook.

That's what I tried to do. I still don't know how to use git properly.

> In addition it would be nice to add an example with reload like [#749 (comment)](https://github.com/pyiron/pyiron/pull/749#issuecomment-647034010)

Yes, I totally agree. As I said, I'm only waiting for @pmrv to finish the stuff right now.

But ok, I'll try to figure out how to entirely separate this pull request from @pmrv 's one

**Comment by samwaseda** [comment]
So the test notebook is done (which means this pull request is done). I still don't understand what's happening to all the other files but I guess @jan-janssen will figure it out :D

**Pull request merged**
