### PR TITLE
Condition if no unoccupied states are there

### PR DESCRIPTION
**Pull request by sudarsan-surendralal**
Fixing parsing on OUTCAR files (when no unoccupied states are present)

### CODE REVIEW

**Comment by jan-janssen** [comment]
Does it make sense to add Lifangs OUTCAR file or a reduced version of that OUTCAR file to the tests?

**Comment by sudarsan-surendralal** [comment]
> 
> 
> Does it make sense to add Lifangs OUTCAR file or a reduced version of that OUTCAR file to the tests?

It's a little large (1.2 MB). Plus the content of the OUTCAR isn't that unique/different. It's just that the function should have considered this special case.

**Comment by jan-janssen** [comment]
Alternatively can we add this special case to one of the existing OUTCAR files?

**Comment by lfzhu-phys** [comment]
@jan-janssen @sudarsan-surendralal Thanks a lot for the analysis:)

**Comment by sudarsan-surendralal** [comment]
> 
> 
> Alternatively can we add this special case to one of the existing OUTCAR files?

I've done this now.

**Review by jan-janssen — APPROVED** [review]
Looks good to me

**Comment by sudarsan-surendralal** [comment]
@lfzhu-phys, you should be able to work now with the master branch.

**Comment by lfzhu-phys** [comment]
@sudarsan-surendralal Great, thanks a lot, I will try it out:)

**Pull request merged**
