### PR TITLE
Added Yaff module to latest master from hpc_ugent

### PR DESCRIPTION
**Pull request by SanderBorgmans**

### CODE REVIEW

**Comment by jan-janssen** [comment]
I am fine with adding `yaff` to the dependencies as well, but for `quickff` I am not sure if there is a conda package available.

**Comment by jan-janssen** [comment]
Please wait for https://github.com/pyiron/pyiron/pull/548#issuecomment-597803595 Before merging.

**Comment by jan-janssen** [comment]
I get: 

```
======================================================================
2331ERROR: yaff.test_yaff (unittest.loader._FailedTest)
2332----------------------------------------------------------------------
2333ImportError: Failed to import test module: yaff.test_yaff
2334Traceback (most recent call last):
2335  File "/home/travis/miniconda/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
2336    module = self._get_module_from_name(name)
2337  File "/home/travis/miniconda/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
2338    __import__(name)
2339  File "/home/travis/build/pyiron/pyiron/tests/yaff/test_yaff.py", line 16, in <module>
2340    from pyiron.yaff.yaff import YaffInput
2341  File "/home/travis/build/pyiron/pyiron/pyiron/yaff/yaff.py", line 7, in <module>
2342    from yaff import System, log, ForceField
2343ImportError: cannot import name 'System' from 'yaff' (/home/travis/build/pyiron/pyiron/tests/yaff/__init__.py)
```

But  `yaff-1.4.2  py37h516909a_3` is installed.

**Comment by SanderBorgmans** [comment]
> I get:
> 
> ```
> ======================================================================
> 2331ERROR: yaff.test_yaff (unittest.loader._FailedTest)
> 2332----------------------------------------------------------------------
> 2333ImportError: Failed to import test module: yaff.test_yaff
> 2334Traceback (most recent call last):
> 2335  File "/home/travis/miniconda/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
> 2336    module = self._get_module_from_name(name)
> 2337  File "/home/travis/miniconda/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
> 2338    __import__(name)
> 2339  File "/home/travis/build/pyiron/pyiron/tests/yaff/test_yaff.py", line 16, in <module>
> 2340    from pyiron.yaff.yaff import YaffInput
> 2341  File "/home/travis/build/pyiron/pyiron/pyiron/yaff/yaff.py", line 7, in <module>
> 2342    from yaff import System, log, ForceField
> 2343ImportError: cannot import name 'System' from 'yaff' (/home/travis/build/pyiron/pyiron/tests/yaff/__init__.py)
> ```
> 
> But `yaff-1.4.2 py37h516909a_3` is installed.

@jan-janssen this commit was not meant to work yet, sorry! I just wanted a clean install on my own conda environment on the HPC, with the latest commits.

**Comment by SanderBorgmans** [comment]
@jan-janssen I think with these extra tests the coverage should be fine, however, something seems to go wrong with one of the tests which does not happen locally. I think it has to do with 

https://github.com/SanderBorgmans/pyiron/blob/b184b06056183d44ae61f6ed1f16e7d10571650c/pyiron/yaff/yaff.py#L326

I don't think this file is being loaded correctly, while it should be available:

https://github.com/SanderBorgmans/pyiron/blob/b184b06056183d44ae61f6ed1f16e7d10571650c/tests/yaff_module/test_yaff.py#L431

Could you take a look? 
FYI: I uploaded a QuickFF pacakge to PyPI (https://pypi.org/project/QuickFF/2.2.4/).
I hope it works..

**Comment by jan-janssen** [comment]
I updated the quickff conda package - https://github.com/conda-forge/quickff-feedstock/pull/1 - Should I add you as a maintainer?

**Comment by jan-janssen** [comment]
It seems like only the Windows test failed: 

```
======================================================================
1375FAIL: test_run_metadynamics_complete (yaff_module.test_yaff.TestYaff)
1376----------------------------------------------------------------------
1377Traceback (most recent call last):
1378  File "C:\projects\pyiron\tests\yaff_module\test_yaff.py", line 445, in test_run_metadynamics_complete
1379    self.assertTrue(all([node in hdf_nodes for node in nodes]))
1380AssertionError: False is not true
1381
1382----------------------------------------------------------------------
1383Ran 437 tests in 244.384s
1384
1385FAILED (failures=1, skipped=4)
1386
```

**Comment by jan-janssen** [comment]
@SanderBorgmans The issue is in https://github.com/sanderborgmans/pyiron/blob/yaff_module/pyiron/yaff/yaff.py#L690 on windows this results in a \ while on linux and mac its a '/' therefore https://github.com/sanderborgmans/pyiron/blob/yaff_module/pyiron/yaff/yaff.py#L326 fails on windows.

**Comment by SanderBorgmans** [comment]
> @SanderBorgmans The issue is in https://github.com/sanderborgmans/pyiron/blob/yaff_module/pyiron/yaff/yaff.py#L690 on windows this results in a `\` while on linux and mac its a `/` therefore https://github.com/sanderborgmans/pyiron/blob/yaff_module/pyiron/yaff/yaff.py#L326 fails on windows.

Good find! How can we solve this?

**Comment by jan-janssen** [comment]
My recommendation would be to replace `os.path.join()` with `posixpath.join()` .

**Comment by SanderBorgmans** [comment]
> I updated the quickff conda package - [conda-forge/quickff-feedstock#1](https://github.com/conda-forge/quickff-feedstock/pull/1) - Should I add you as a maintainer?

I did not see this comment, sorry! Sure!

**Comment by jan-janssen** [comment]
> > I updated the quickff conda package - [conda-forge/quickff-feedstock#1](https://github.com/conda-forge/quickff-feedstock/pull/1) - Should I add you as a maintainer?
> 
> I did not see this comment, sorry! Sure!

Done in https://github.com/conda-forge/quickff-feedstock/pull/2 - you should get an email in a minute.

**Pull request merged**
