### PR TITLE
bugfix set_empty_states

### PR DESCRIPTION
**Pull request by FeLoch**
See #520

### CODE REVIEW

**Comment by jan-janssen** [comment]
@samwaseda Can you take a look? For me it looks fine.

**Comment by samwaseda** [comment]
Looks great :) But was it really a bug?

Maybe a small unit test...

**Comment by samwaseda** [comment]
> Looks great :) But was it really a bug?
> 

ok now I understood what was the problem in the previous version

**Comment by samwaseda** [comment]
Very good!

**Pull request merged**
